### ISSUE TITLE
Partial series and field keys from InfluxDB 1.2.0

### ISSUE THREAD

**Issue by choffee** [InfluxGraph/influxgraph#24] opened 2017-02-02 17:49 UTC
We have ~75k series and when requesting the series list influxdb, 1.1.0, is returning a partial set of results, I think due to memory limits. influxgraph is then not noticing this that just saving the partial results.
I tried increacing the http_row_limit in influxdb to no effect.
Reducing the LOADER_LIMIT in constants.py to 5000 has fixed it for me but seems more of a hack.
It should handle the server setting the partial flag.
I think the partial flag may be returned in a different place in the json returned if it's a server side limit that you have hit. Maybe this is really a bug in python-influxdb?

**Comment by choffee** [comment] 2017-02-02 17:55
When I try the query on the cmd line using curl I get: 

`curl 'http://localhost:8086/query?db=graphite&epoch=s&q=SHOW+SERIES+LIMIT+10000+OFFSET+0&pretty=true' |tail`


                        ]
                    ],
                    "partial": true
                }
            ],
            "partial": true
        }
    ]
    }


Whereas with a limit set to 5000 it just returns the 5000 results.

**Comment by pkittenis** [comment] 2017-02-05 16:07
Is there anything in influxdb logs to indicate what is causing partial results to be returned? Influxgraph is regularly used with millions of series in the DB but have not come across this before.

The loader limit should be configurable initially, beyond that it depends on the behaviour of the client if this is something that can be handled in influxgraph code.

**Comment by pkittenis** [comment] 2017-02-07 18:15
Hi @choffee, will need some more info per above to see if this can be handled client side - doubt it can but to make sure. 

There [are changes coming](https://github.com/InfluxGraph/influxgraph/tree/loader_limit_config) that make loader limit configurable. 

As whether or not influxdb returns partial results seems to depend on configuration, available memory, data size and so on it would be up to user to set an appropriate value for loader limit depending on setup.

**Comment by pkittenis** [comment] 2017-02-08 12:03
Loader limit now configurable as of `1.2.0`. Issue will be closed in a few days if no further info provided.

**Comment by pkittenis** [comment] 2017-02-08 13:10
This can be caused by a [change in influxdb 1.2.0](https://github.com/influxdata/influxdb/issues/7962) which truncates series lists over 10k. Default has been set to 10k accordingly in the [1.2.1](https://github.com/InfluxGraph/influxgraph/releases/tag/1.2.1) release

**Comment by pkittenis** [comment] 2017-02-08 13:28
Looks like field list is also affected, same issue. Needs feedback from influxdb team on expected behaviour. Suggest to stick with influxdb `1.1.x` in the mean time.

**Comment by pkittenis** [comment] 2017-02-09 17:30
Pagination is now implemented, however, there seems to be  [a blocking issue with influxdb and non-chunked queries](https://github.com/influxdata/influxdb/issues/7980).

**Comment by pkittenis** [comment] 2017-02-16 15:53
See also [pull request on python client](https://github.com/influxdata/influxdb-python/pull/418) for chunked response support.

**Comment by pkittenis** [comment] 2017-03-01 11:54
Currently blocked by new upstream client release with chunked response support.

**Comment by pkittenis** [comment] 2017-03-21 11:04
FYI, Influx has reverted `max-row-limit` change in [1.2.2](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v122-2017-03-14)

Pagination support has been added by myself to influxdb python client, though not released as of now.

Show field keys issue not resolved upstream but also not applicable to this issue.

Pagination for field list is implemented in influxgraph and blocked by both influxdb issue and influxdb python client release with pagination support.

Loader limit in influxgraph is configurable as of `1.2.0`.

Therefore closing this.

**Closed as completed by pkittenis** 2017-03-21 11:04 UTC
Labels: enhancement
